sudo: required
dist: trusty
language: rust
# cache dependencies: https://docs.travis-ci.com/user/caching/#Rust-Cargo-cache
cache:
  directories:
    - ~/.cargo
# run builds for all the trains (and more)
rust:
  - 1.23.0 # test against minimum Rust version supported
  - stable
  - beta
  - nightly
os:
  - linux
  - osx
before_install:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then ulimit -n 1024; fi
script:
  - echo "Running Rusoto tests" && cargo update && cargo test --all -v
  - |
      echo "Building integration tests" &&
      ( cd integration_tests && \
        cargo check --tests --features "all" )
  - |
      echo "Running cargo docs on stable Rust on Linux" &&
      if [[ "$TRAVIS_OS_NAME" == "linux" && "$TRAVIS_RUST_VERSION" == "stable" ]]; then
        cargo doc --all --no-deps
      fi
after_success:
  # upload the documentation from the build if it's from Rust stable, Linux and not a pull request:
  - |
      if [[ "$TRAVIS_OS_NAME" == "linux" && "$TRAVIS_RUST_VERSION" == "stable" && "$TRAVIS_PULL_REQUEST" == false ]]; then
        echo '<meta http-equiv=refresh content=0;url=rusoto_core/index.html>' > target/doc/index.html \
        && mkdir target/doc/rusoto/ && echo '<meta http-equiv=refresh content=0;url=../rusoto_core/index.html>' > target/doc/rusoto/index.html \
        && sudo pip install ghp-import && ghp-import -n target/doc \
        && git push -fq https://${GH_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git gh-pages \
        && cd ..
      fi
env:
  global:
    - RUST_BACKTRACE=1
    - CARGO_INCREMENTAL=0
branches:
  only:
    - master
    - auto
notifications:
  email: false
matrix:
  fast_finish: true
  allow_failures:
    - rust: nightly
