sudo: required
dist: trusty
language: rust
# cache dependencies: https://docs.travis-ci.com/user/caching/#Rust-Cargo-cache
cache: cargo
# run builds for all the trains (and more)
rust:
  - stable
  - beta
  - nightly
os:
  - linux
  - osx
addons:
  apt:
    packages:
      - python3-requests
cache:
  directories:
    - $HOME/.cargo
before_install:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then ulimit -n 1024; fi
  - rustup install nightly
script:
  - |
      echo "Generating service crates..." &&
      ( cd service_crategen && \
        cargo +nightly run -- generate -c ./services.json -o ../rusoto/services )
  - echo "Running Rusoto tests" && cargo update && cargo test --lib --all -v
  - |
      echo "Building integration tests" &&
      ( cd integration_tests && \
        cargo test --features "all" --no-run )
  - |
      echo "Running cargo docs on stable Rust on Linux" &&
      if [[ "$TRAVIS_OS_NAME" == "linux" && "$TRAVIS_RUST_VERSION" == "stable" ]]; then
        cargo doc --all --no-deps
      fi
  - |
      echo "Running Ceph integration tests"
      if [[ "$TRAVIS_OS_NAME" == "linux" && "$TRAVIS_RUST_VERSION" == "stable" ]]; then
        (
          export AWS_ACCESS_KEY_ID=ANTN35UAENTS5UIAEATD
          export AWS_SECRET_ACCESS_KEY=TtnuieannGt2rGuie2t8Tt7urarg5nauedRndrur
          export S3_ENDPOINT='http://localhost'
          cd integration_tests && \
          ./docker_test_run.py \
              --docker-image "ceph/demo" \
              --run-opt=--env=CEPH_DEMO_ACCESS_KEY=$AWS_ACCESS_KEY_ID \
              --run-opt=--env=CEPH_DEMO_SECRET_KEY=$AWS_SECRET_ACCESS_KEY \
              --run-opt=--env=CEPH_DEMO_UID=demo_uid \
              --run-opt=--env=MON_IP=127.0.0.1 \
              --run-opt=--env=CEPH_PUBLIC_NETWORK=0.0.0.0/0 \
              --run-opt=--hostname=localhost \
              -- cargo test --features s3,disable_ceph_unsupported
        )
      fi
  - |
      echo "Running Minio integration tests"
      if [[ "$TRAVIS_OS_NAME" == "linux" && "$TRAVIS_RUST_VERSION" == "stable" ]]; then
        (
          export AWS_ACCESS_KEY_ID=ANTN35UAENTS5UIAEATD
          export AWS_SECRET_ACCESS_KEY=TtnuieannGt2rGuie2t8Tt7urarg5nauedRndrur
          export S3_ENDPOINT='http://localhost:9000'
          cd integration_tests && \
          ./docker_test_run.py \
              --docker-image="minio/minio" \
              --docker-image="minio/minio:edge" \
              --port=9000 \
              --run-opt=--env=MINIO_ACCESS_KEY=$AWS_ACCESS_KEY_ID \
              --run-opt=--env=MINIO_SECRET_KEY=$AWS_SECRET_ACCESS_KEY \
              --run-opt=--env=MINIO_DOMAIN=localhost \
              --run-arg=server \
              --run-arg=/home/shared \
              -- cargo test --features s3,disable_minio_unsupported
        )
      fi
after_success:
  # upload the documentation from the build if it's from Rust stable, Linux and not a pull request:
  - |
      if [[ "$TRAVIS_OS_NAME" == "linux" && "$TRAVIS_RUST_VERSION" == "stable" && "$TRAVIS_PULL_REQUEST" == false ]]; then
        echo '<meta http-equiv=refresh content=0;url=rusoto_core/index.html>' > target/doc/index.html \
        && mkdir target/doc/rusoto/ && echo '<meta http-equiv=refresh content=0;url=../rusoto_core/index.html>' > target/doc/rusoto/index.html \
        && sudo pip install ghp-import && ghp-import -n target/doc \
        && git push -fq https://${GH_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git gh-pages \
        && cd ..
      fi
env:
  global:
    - RUST_BACKTRACE=1

branches:
  only:
    - master
    - auto
notifications:
  email: false
matrix:
  fast_finish: true
  allow_failures:
    - rust: nightly
